import { GoogleGenAI } from "@google/genai";
import { DevConfig } from "../types";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key is missing. Please set process.env.API_KEY.");
  }
  return new GoogleGenAI({ apiKey });
};

export const generatePostcard = async (
  mapImageBase64: string,
  userPrompt: string,
  modelName: string = 'gemini-2.5-flash-image',
  userImageBase64?: string,
  aspectRatio: string = '4:3',
  devConfig?: DevConfig,
  locationName: string = ""
): Promise<string> => {
  try {
    const ai = getClient();
    
    // Clean base64 strings
    const cleanMapBase64 = mapImageBase64.replace(/^data:image\/(png|jpeg|jpg);base64,/, "");
    const cleanUserBase64 = userImageBase64 ? userImageBase64.replace(/^data:image\/(png|jpeg|jpg);base64,/, "") : null;

    let systemInstruction = "";
    
    // Logic to handle empty location names naturally
    const hasLocationName = locationName && locationName.trim().length > 0;
    const locationContext = hasLocationName ? `The location is "${locationName}".` : "The specific location name is unknown, so deduce the vibe from the map structure itself.";
    const typographyRule = hasLocationName 
      ? `3. TYPOGRAPHY: You MUST artistically integrate the text "${locationName}" into the image. It should look like a professional poster title.` 
      : `3. TYPOGRAPHY: Do NOT add specific location text if you don't know it. You may add generic artistic text like "Greetings" or "Travel" ONLY if it fits the style, otherwise keep it text-free.`;

    // 1. Developer Custom Override
    if (devConfig?.useCustomPrompt && devConfig.customSystemInstruction) {
      systemInstruction = devConfig.customSystemInstruction;
    } 
    // 2. V3 "Map as Wireframe" Logic
    else if (devConfig?.useV2Prompt) {
       systemInstruction = `
        ROLE: Master Cartographic Artist & Postcard Designer.

        TASK:
        You are provided with a [Map Image]. Your job is to COLOR and TEXTURIZE this map to turn it into an art piece.
        
        CRITICAL INSTRUCTION - MAP INTEGRATION:
        - The [Map Image] is your WIREFRAME / LINE ART.
        - DO NOT HALLUCINATE NEW GEOGRAPHY.
        - TRACE the roads: They must become streets/canals/paths in the final image.
        - TRACE the blocks: They must become buildings/forests/parks.
        - The goal is that if I overlay the original map on your output, the streets would ALIGN.

        DESIGN & COMPOSITION:
        1. PERSPECTIVE: Maintain the top-down or slightly tilted (isometric) view of the map. Do not change it to a street-level photo.
        2. CONTEXT: ${locationContext} Use architectural styles relevant to this context.
        ${typographyRule}
        4. USER INTEGRATION: (If User Photo is provided) The user is the traveler standing IN this map world (e.g., standing on one of the map's streets), looking at the scenery.

        ARTISTIC STYLE:
        ${userPrompt}

        CONSTRAINTS:
        - FULL BLEED. Fill the canvas.
        - NO MAP UI. Turn pins/buttons into trees or bushes.
        - High fidelity textures.
        
        ${cleanUserBase64 ? `
        USER PHOTO INSTRUCTION:
        - A photo of the user is provided. 
        - REDRAW the person into the scene. 
        - Match lighting and style.
        ` : ''}

        Output ONLY the raw image file content.
       `;
    }
    // 3. Fallback
    else {
      systemInstruction = `Create a postcard. ${hasLocationName ? `Location: ${locationName}` : ''}. Style: ${userPrompt}. Use the map as background.`;
    }

    const config: any = {
      imageConfig: {
        aspectRatio: aspectRatio
      }
    };

    if (modelName === 'gemini-3-pro-image-preview') {
      config.imageConfig.imageSize = "1K";
    }

    const parts: any[] = [
      { text: systemInstruction },
      {
        inlineData: {
          mimeType: 'image/png',
          data: cleanMapBase64
        }
      }
    ];

    if (cleanUserBase64) {
      parts.push({
        inlineData: {
          mimeType: 'image/jpeg',
          data: cleanUserBase64
        }
      });
    }

    const response = await ai.models.generateContent({
      model: modelName,
      contents: { parts },
      config: config
    });

    let resultImage = "";
    const responseParts = response.candidates?.[0]?.content?.parts;
    
    if (responseParts) {
      for (const part of responseParts) {
        if (part.inlineData && part.inlineData.data) {
          resultImage = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!resultImage) {
      throw new Error("No image generated by the model.");
    }

    return resultImage;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const generatePostcardBack = async (
  styleId: string,
  modelName: string = 'gemini-2.5-flash-image',
  aspectRatio: string = '4:3'
): Promise<string> => {
  try {
    const ai = getClient();
    
    let styleDetails = "";
    switch(styleId) {
      case 'vintage':
        styleDetails = "Aged yellowed paper texture with coffee stains. Antique victorian border.";
        break;
      case 'watercolor':
        styleDetails = "Clean white cold-press watercolor paper texture. Soft floral corners.";
        break;
      case 'cyberpunk':
        styleDetails = "Dark digital slate background. Neon blue grid lines. Holographic elements.";
        break;
      case 'sketch':
        styleDetails = "Rough sketchbook paper texture. Charcoal pencil lines.";
        break;
      case 'oil':
        styleDetails = "Canvas cloth texture background. Elegant painted border.";
        break;
      case 'ink':
        styleDetails = "Aged rice paper texture. Vertical divider line painted with brush.";
        break;
      default:
        styleDetails = "Standard off-white cardstock texture.";
    }

    const config: any = {
      imageConfig: {
        aspectRatio: aspectRatio
      }
    };

    if (modelName === 'gemini-3-pro-image-preview') {
      config.imageConfig.imageSize = "1K";
    }

    const prompt = `
      Generate a FLAT, 2D GRAPHIC DESIGN TEXTURE for the BACK side of a postcard.
      Full Bleed. No 3D perspective.
      Visual Style: ${styleDetails}
      Elements: Divider line, address lines, stamp box.
    `;

    const response = await ai.models.generateContent({
      model: modelName,
      contents: { parts: [{ text: prompt }] },
      config: config
    });

    let resultImage = "";
    const responseParts = response.candidates?.[0]?.content?.parts;
    
    if (responseParts) {
      for (const part of responseParts) {
        if (part.inlineData && part.inlineData.data) {
          resultImage = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }
    
    return resultImage;

  } catch (error) {
    console.error("Back generation failed:", error);
    return "";
  }
}